metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

fields:
  custom_host: "elk-lab"
fields_under_root: true

setup.kibana:
  host: "${KIBANA_HOST}"
  username: "${KIBANA_USERNAME}"
  password: "${KIBANA_PASSWORD}"
  ssl:
    certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]
# 各種 modules（system、elasticsearch 等）收集到的 metrics 寫到 metricbeat-*
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}"]
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  ssl:
    certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]

# Metricbeat 自我監控已關閉
# 理由：生產環境應專注於業務數據監控，若沒有資料進來應該由告警觸發人工介入，
# 而非依賴監控 Metricbeat 自身的狀態。這可以減少不必要的監控數據量。
monitoring:
  enabled: false

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_process_metadata: ~

logging.to_files: false
logging.to_stderr: true